export const userActionTypes = {
  LOGIN: 'LOGIN',
  LAYOUT: 'LAYOUT',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_TOKEN: 'SET_TOKEN',
  CLEAN_TOKEN: 'CLEAN_TOKEN',
  CHANGE_LOGIN_STATUS: 'CHANGE_LOGIN_STATUS',
};
